// Round-trip + byte-format characterization for fox_monitor::sidecar.
//
// Pins the on-disk format write() emits (header line + four double-quoted
// KEY="value" assignments, vectors space-joined) byte-for-byte, then proves
// read() recovers every field. Also covers the empty-Layout round-trip and
// the missing-file → empty-Layout contract that call sites rely on.
//
// No fox-common dependency — links only libfox-monitor.

#include "../sidecar.hpp"

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

namespace fs = std::filesystem;
using namespace fox_monitor::sidecar;

namespace {

int failed = 0;

void check(const char* what, bool ok) {
    if (!ok) { std::fprintf(stderr, "FAIL %s\n", what); ++failed; }
}

std::string slurp(const fs::path& p) {
    std::ifstream in(p);
    return std::string((std::istreambuf_iterator<char>(in)),
                       std::istreambuf_iterator<char>());
}

bool vec_eq(const std::vector<std::string>& a,
            const std::vector<std::string>& b) {
    if (a.size() != b.size()) return false;
    for (size_t i = 0; i < a.size(); ++i)
        if (a[i] != b[i]) return false;
    return true;
}

}  // namespace

int main() {
    fs::path dir = fs::temp_directory_path() / "fox-monitor-sidecar-test";
    std::error_code ec;
    fs::remove_all(dir, ec);
    fs::create_directories(dir, ec);

    // ── (1) populated Layout: byte-exact write + full round-trip ──────
    {
        Layout l;
        l.primary             = "eDP-1";
        l.portrait_outputs    = {"DP-2"};
        l.secondary_outputs   = {"DP-2"};
        l.monitor_resolutions = {"eDP-1:1920x1080", "DP-2:2160x3840"};

        fs::path p = dir / "monitor-layout.conf";
        check("(1) write returns true", write(p, l));

        const std::string expected =
            "# Auto-generated by fox-install --monitors\n"
            "PRIMARY=\"eDP-1\"\n"
            "PORTRAIT_OUTPUTS=\"DP-2\"\n"
            "SECONDARY_OUTPUTS=\"DP-2\"\n"
            "MONITOR_RESOLUTIONS=\"eDP-1:1920x1080 DP-2:2160x3840\"\n";
        std::string actual = slurp(p);
        check("(1) byte-exact on-disk format", actual == expected);

        Layout back = read(p);
        check("(1) round-trip primary",   back.primary == l.primary);
        check("(1) round-trip portrait",  vec_eq(back.portrait_outputs, l.portrait_outputs));
        check("(1) round-trip secondary", vec_eq(back.secondary_outputs, l.secondary_outputs));
        check("(1) round-trip resolutions",
              vec_eq(back.monitor_resolutions, l.monitor_resolutions));
    }

    // ── (2) empty Layout round-trip — empty quoted values, vectors empty ──
    {
        Layout l;  // all-empty
        fs::path p = dir / "empty.conf";
        check("(2) write empty returns true", write(p, l));

        const std::string expected =
            "# Auto-generated by fox-install --monitors\n"
            "PRIMARY=\"\"\n"
            "PORTRAIT_OUTPUTS=\"\"\n"
            "SECONDARY_OUTPUTS=\"\"\n"
            "MONITOR_RESOLUTIONS=\"\"\n";
        check("(2) byte-exact empty format", slurp(p) == expected);

        Layout back = read(p);
        check("(2) empty round-trip primary",   back.primary.empty());
        check("(2) empty round-trip portrait",  back.portrait_outputs.empty());
        check("(2) empty round-trip secondary", back.secondary_outputs.empty());
        check("(2) empty round-trip resolutions", back.monitor_resolutions.empty());
    }

    // ── (3) missing file → empty Layout (call-site contract) ──────────
    {
        Layout back = read(dir / "does-not-exist.conf");
        check("(3) missing-file → empty primary",     back.primary.empty());
        check("(3) missing-file → empty portrait",    back.portrait_outputs.empty());
        check("(3) missing-file → empty secondary",   back.secondary_outputs.empty());
        check("(3) missing-file → empty resolutions", back.monitor_resolutions.empty());
    }

    fs::remove_all(dir, ec);

    if (failed == 0) std::printf("test_sidecar: OK\n");
    return failed ? 1 : 0;
}
